# yaml-language-server: $schema=./quartz/plugins/quartz-plugins.schema.json
configuration:
  pageTitle: 🐢 Shagshag
  pageTitleSuffix: " - Shagshag"
  enableSPA: true
  enablePopovers: true
  analytics:
    provider: null
  locale: fr-FR
  baseUrl: www.shagshag.net
  ignorePatterns:
    - private
    - templates
    - .obsidian
  theme:
    fontOrigin: local
    cdnCaching: false
    typography:
      header: system-ui
      body: system-ui
      code: ui-monospace
    colors:
      lightMode:
        light: "#faf8f8"
        lightgray: "#e5e5e5"
        gray: "#b8b8b8"
        darkgray: "#4e4e4e"
        dark: "#2b2b2b"
        secondary: "#284b63"
        tertiary: "#84a59d"
        highlight: rgba(143, 159, 169, 0.15)
        textHighlight: "#fff23688"
      darkMode:
        light: "#161618"
        lightgray: "#393639"
        gray: "#646464"
        darkgray: "#d4d4d4"
        dark: "#ebebec"
        secondary: "#7b97aa"
        tertiary: "#84a59d"
        highlight: rgba(143, 159, 169, 0.15)
        textHighlight: "#b3aa0288"
plugins:
  - source: github:quartz-community/created-modified-date
    enabled: true
    options:
      defaultDateType: created
      priority:
        - frontmatter
        - git
        - filesystem
    order: 10
  - source: github:quartz-community/obsidian-flavored-markdown
    enabled: true
    options:
      comments: true
      highlight: true
      wikilinks: true
      callouts: true
      mermaid: true
      parseTags: true
      parseArrows: true
      parseBlockReferences: true
      enableInHtmlEmbed: false
      enableYouTubeEmbed: true
      enableVideoEmbed: true
      enableCheckbox: true
    order: 30
  - source: github:quartz-community/github-flavored-markdown
    enabled: true
    order: 40
  - source: github:quartz-community/table-of-contents
    enabled: true
    order: 50
    layout:
      position: right
      priority: 30
  - source: github:quartz-community/crawl-links
    enabled: true
    options:
      markdownLinkResolution: shortest
    order: 60
  - source: github:quartz-community/description
    enabled: true
    order: 70
  - source: github:quartz-community/latex
    enabled: false
    options:
      renderEngine: katex
    order: 80
  - source: github:quartz-community/citations
    enabled: false
    order: 85
  - source: github:quartz-community/hard-line-breaks
    enabled: true
    order: 90
  - source: github:quartz-community/ox-hugo
    enabled: false
    order: 91
  - source: github:quartz-community/roam
    enabled: false
    order: 92
  - source: github:quartz-community/remove-draft
    enabled: true
  - source: github:quartz-community/explicit-publish
    enabled: false
  - source: github:quartz-community/unlisted-pages
    enabled: true
    options: {}
    order: 45
  - source: github:quartz-community/encrypted-pages
    enabled: true
    options:
      iterations: 600000
      passwordField: password
      unlistWhenEncrypted: false
      outputPath: static/encryptedContentIndex.json
  - source: github:quartz-community/stacked-pages
    enabled: false
    layout:
      position: afterBody
      priority: 50
      display: all
  - source: github:quartz-community/alias-redirects
    enabled: true
  - source: github:Shagshag/redirects-file
    enabled: true
    options:
      aliases: true
      redirects:
        - from: "culture/la-célébrité"
          to: "culture/la-celebrite"
        - from: "culture/qui-répond-de-la-machine---d'ibm-aux-machines-d'asimov"
          to: "culture/qui-repond-de-la-machine-d-ibm-aux-machines-d-asimov"
        - from: "développement/14-minutes-de-cache-warmup-sur-efs---quand-un-back-office-prestashop-devient-injoignable"
          to: "developpement/14-minutes-de-cache-warmup-sur-efs-quand-un-back-office-prestashop-devient-injoignable"
        - from: "développement/9-go-de-cache-twig---un-template-compilé-par-page-dans-le-back-office-prestashop-8"
          to: "developpement/9-go-de-cache-twig-un-template-compile-par-page-dans-le-back-office-prestashop-8"
        - from: "développement/accéder-à-une-variable-css-en-javascript"
          to: "developpement/acceder-a-une-variable-css-en-javascript"
        - from: "développement/activer-les-hooks-dans-une-page-cms-prestashop"
          to: "developpement/activer-les-hooks-dans-une-page-cms-prestashop"
        - from: "développement/afficher-les-requêtes-exécutées-par-le-serveur-sql"
          to: "developpement/afficher-les-requetes-executees-par-le-serveur-sql"
        - from: "développement/alternative-à-parse_str-sans-limitation"
          to: "developpement/alternative-a-parse_str-sans-limitation"
        - from: "développement/anonymiser-les-données-de-prestashop"
          to: "developpement/anonymiser-les-donnees-de-prestashop"
        - from: "développement/autoriser-les-images-avec-des-longs-id-dans-prestashop"
          to: "developpement/autoriser-les-images-avec-des-longs-id-dans-prestashop"
        - from: "développement/avoir-un-point-comme-séparateur-dans-gnome-calculator"
          to: "developpement/avoir-un-point-comme-separateur-dans-gnome-calculator"
        - from: "développement/contact-form-7-et-popup-maker"
          to: "developpement/contact-form-7-et-popup-maker"
        - from: "développement/convertir-une-date-excel-en-timestamp"
          to: "developpement/convertir-une-date-excel-en-timestamp"
        - from: "développement/corriger-les-urls-propres-de-quartz-sur-sevalla"
          to: "developpement/corriger-les-urls-propres-de-quartz-sur-sevalla"
        - from: "développement/créer-une-table-dont-l'auto-incrément-dépend-d'une-requête-sql"
          to: "developpement/creer-une-table-dont-l-auto-increment-depend-d-une-requete-sql"
        - from: "développement/destinataires-de-mails-avec-contact-form-7"
          to: "developpement/destinataires-de-mails-avec-contact-form-7"
        - from: "développement/décodeur-de-code-php"
          to: "developpement/decodeur-de-code-php"
        - from: "développement/ecs-exec-en-pratique---retrouver-sa-tâche,-ouvrir-la-session,-passer-un-script-sans-se-battre-avec-le-quoting"
          to: "developpement/ecs-exec-en-pratique-retrouver-sa-tache-ouvrir-la-session-passer-un-script-sans-se-battre-avec-le-quoting"
        - from: "développement/erreur-xxx.live-is-not-a-function-dans-wordpress"
          to: "developpement/erreur-xxx.live-is-not-a-function-dans-wordpress"
        - from: "développement/exemple-d'override-pour-prestashop"
          to: "developpement/exemple-d-override-pour-prestashop"
        - from: "développement/exporter-toutes-les-visuels-produits-originaux-d'un-prestashop"
          to: "developpement/exporter-toutes-les-visuels-produits-originaux-d-un-prestashop"
        - from: "développement/exécuter-un-script-prestashop-en-ligne-de-commande"
          to: "developpement/executer-un-script-prestashop-en-ligne-de-commande"
        - from: "développement/forcer-index.php-avec-wordpress"
          to: "developpement/forcer-index.php-avec-wordpress"
        - from: "développement/installer-l'extension-ssh2-pour-php-sous-macos"
          to: "developpement/installer-l-extension-ssh2-pour-php-sous-macos"
        - from: "développement/insérer-une-ligne-vide-en-sql"
          to: "developpement/inserer-une-ligne-vide-en-sql"
        - from: "développement/le-dockerfile-disait-`fr_fr.utf-8`.-php-voyait-`c.utf-8`"
          to: "developpement/le-dockerfile-disait-fr_fr.utf-8-.-php-voyait-c.utf-8"
        - from: "développement/migrer-un-site-wordpress"
          to: "developpement/migrer-un-site-wordpress"
        - from: "développement/ne-pas-utiliser-de-champs-float-dans-mysql"
          to: "developpement/ne-pas-utiliser-de-champs-float-dans-mysql"
        - from: "développement/optimisation-de-quartz"
          to: "developpement/optimisation-de-quartz"
        - from: "développement/programmer-les-popups-de-popup-builder"
          to: "developpement/programmer-les-popups-de-popup-builder"
        - from: "développement/rediriger-les-fiches-produits-dans-woocommerce"
          to: "developpement/rediriger-les-fiches-produits-dans-woocommerce"
        - from: "développement/remplacer-les-ã©-dans-une-table-sql"
          to: "developpement/remplacer-les-a©-dans-une-table-sql"
        - from: "développement/sauvegarde-automatique-sur-ftp"
          to: "developpement/sauvegarde-automatique-sur-ftp"
        - from: "développement/supprimer-les-notices-du-mode-debug-de-prestashop"
          to: "developpement/supprimer-les-notices-du-mode-debug-de-prestashop"
        - from: "développement/supprimer-un-site-wordpress"
          to: "developpement/supprimer-un-site-wordpress"
        - from: "développement/supprimer-une-boutique-prestashop"
          to: "developpement/supprimer-une-boutique-prestashop"
        - from: "développement/télécharger-un-dossier-depuis-google-drive-à-partir-du-terminal"
          to: "developpement/telecharger-un-dossier-depuis-google-drive-a-partir-du-terminal"
        - from: "développement/télécharger-un-fichier-depuis-google-drive-à-partir-du-terminal"
          to: "developpement/telecharger-un-fichier-depuis-google-drive-a-partir-du-terminal"
        - from: "développement/utiliser-bootstrap-dans-une-partie-d'une-page"
          to: "developpement/utiliser-bootstrap-dans-une-partie-d-une-page"
        - from: "développement/utiliser-un-emoji-comme-favicon"
          to: "developpement/utiliser-un-emoji-comme-favicon"
        - from: "développement/vider-un-dossier-en-php"
          to: "developpement/vider-un-dossier-en-php"
        - from: "développement/wordpress-netinstall"
          to: "developpement/wordpress-netinstall"
        - from: "développement/`class`-ou-`alias`,-un-choix-de-conteneur-symfony,-et-un-choix-d'ingénierie"
          to: "developpement/class-ou-alias-un-choix-de-conteneur-symfony-et-un-choix-d-ingenierie"
        - from: "développement/iframe-remplacé-par-i-frame-dans-joomla"
          to: "developpement/iframe-remplace-par-i-frame-dans-joomla"
        - from: "développement/input-date-pour-vue3"
          to: "developpement/input-date-pour-vue3"
        - from: "développement/nl2br-pour-vue3"
          to: "developpement/nl2br-pour-vue3"
        - from: "en/14-minutes-of-cache-warmup-on-efs---when-a-prestashop-back-office-becomes-unreachable"
          to: "en/14-minutes-of-cache-warmup-on-efs-when-a-prestashop-back-office-becomes-unreachable"
        - from: "en/9-gb-of-twig-cache---one-template-compiled-per-page-in-the-prestashop-8-back-office"
          to: "en/9-gb-of-twig-cache-one-template-compiled-per-page-in-the-prestashop-8-back-office"
        - from: "en/the-dockerfile-said-`fr_fr.utf-8`.-php-saw-`c.utf-8`"
          to: "en/the-dockerfile-said-fr_fr.utf-8-.-php-saw-c.utf-8"
        - from: "projets/comment-ce-blog-est-publié"
          to: "projets/comment-ce-blog-est-publie"
        - from: "projets/dur-de-trouver-un-éditeur-markdown"
          to: "projets/dur-de-trouver-un-editeur-markdown"
  - source: github:quartz-community/content-index
    enabled: true
    options:
      enableSiteMap: true
      enableRSS: true
  - source: github:quartz-community/favicon
    enabled: true
  - source: github:quartz-community/og-image
    enabled: false
  - source: github:quartz-community/cname
    enabled: true
  - source: github:quartz-community/canvas-page
    enabled: true
  - source: github:quartz-community/content-page
    enabled: true
  - source: github:quartz-community/folder-page
    enabled: true
  - source: github:quartz-community/tag-page
    enabled: true
  - source: github:quartz-community/explorer
    enabled: true
    layout:
      position: left
      priority: 50
  - source: github:quartz-community/graph
    enabled: false
    layout:
      position: right
      priority: 10
  - source: github:quartz-community/search
    enabled: true
    layout:
      position: left
      priority: 20
      group: toolbar
      groupOptions:
        grow: true
  - source: github:quartz-community/backlinks
    enabled: true
    layout:
      position: right
      priority: 50
  - source: github:quartz-community/article-title
    enabled: false
  - source: github:Shagshag/quartz-markdown-article-title
    enabled: true
    layout:
      position: beforeBody
      priority: 10
  - source: github:quartz-community/content-meta
    enabled: true
    layout:
      position: beforeBody
      priority: 20
  - source: github:quartz-community/tag-list
    enabled: true
    layout:
      position: beforeBody
      priority: 30
  - source: github:quartz-community/page-title
    enabled: false
  - source: github:Shagshag/quartz-html-page-title
    enabled: true
    options:
      html: 🐢<span class="desktop-only"> Shagshag</span>
    layout:
      position: left
      priority: 10
  - source: github:Shagshag/quartz-emoji-favicon
    enabled: true
    options:
      emoji: 🐢
  - source: github:quartz-community/darkmode
    enabled: true
    layout:
      position: left
      priority: 30
      group: toolbar
  - source: github:quartz-community/reader-mode
    enabled: true
    layout:
      position: left
      priority: 35
      group: toolbar
  - source: github:quartz-community/breadcrumbs
    enabled: false
  - source: github:Shagshag/quartz-markdown-breadcrumbs
    enabled: true
    options:
      rootName: Accueil
    layout:
      position: beforeBody
      priority: 5
      condition: not-index
  - source: github:quartz-community/comments
    enabled: false
    options:
      provider: giscus
      options: {}
    layout:
      position: afterBody
      priority: 10
  - source: github:quartz-community/footer
    enabled: true
    options:
      links:
        GitHub: https://github.com/Shagshag
  - source: github:quartz-community/recent-notes
    enabled: false
  - source: github:quartz-community/spacer
    enabled: true
    options: {}
    order: 25
    layout:
      position: left
      priority: 25
      display: mobile-only
  - source: github:quartz-community/bases-page
    enabled: true
    options: {}
    order: 50
  - source: github:quartz-community/note-properties
    enabled: true
    options:
      includeAll: false
      includedProperties:
        - description
        - tags
        - aliases
      excludedProperties: []
      hidePropertiesView: true
      delimiters: ---
      language: yaml
    order: 5
    layout:
      position: beforeBody
      priority: 15
      display: all
  - source:
      name: quartz-themes
      repo: github:saberzero1/quartz-themes
      subdir: plugin
    enabled: false
    options:
      theme: claude
  - source: github:quartz-community/obsidian-plugin-excalidraw
    enabled: false
    options:
      enableInteraction: true
      darkMode: auto
      exportPadding: 20
    order: 50
  - source: github:quartz-community/syntax-highlighting
    enabled: true
    options:
      theme:
        light: github-light
        dark: github-dark
      keepBackground: false
      clipboard: true
      tokenClassification: true
    order: 20
layout:
  groups:
    toolbar:
      priority: 35
      direction: row
      gap: 0.5rem
  byPageType:
    "404":
      positions:
        beforeBody: []
        left: []
        right: []
    content: {}
    folder:
      exclude:
        - reader-mode
      positions:
        right: []
    tag:
      exclude:
        - reader-mode
      positions:
        right: []
    canvas: {}
    bases: {}
